# Microsoft Developer Studio Generated Dependency File, included by dm1_threads.mak
# 19-oct-2002 Renamed to makefile.dep

..\..\src\threads\event.cpp : \
	"..\..\include\dm1\common.h"\
	"..\..\include\dm1\event.h"\
	"..\..\include\dm1\except.h"\
	"..\..\include\dm1\mutex.h"\
	"..\..\include\dm1\port.h"\
	

..\..\src\threads\latch.cpp : \
	"..\..\include\dm1\common.h"\
	"..\..\include\dm1\event.h"\
	"..\..\include\dm1\except.h"\
	"..\..\include\dm1\latch.h"\
	"..\..\include\dm1\list.h"\
	"..\..\include\dm1\mutex.h"\
	"..\..\include\dm1\port.h"\
	"..\..\include\dm1\thread.h"\
	

..\..\src\threads\list.cpp : \
	"..\..\include\dm1\list.h"\
	

..\..\src\threads\monitor.cpp : \
	"..\..\include\dm1\common.h"\
	"..\..\include\dm1\event.h"\
	"..\..\include\dm1\except.h"\
	"..\..\include\dm1\list.h"\
	"..\..\include\dm1\monitor.h"\
	"..\..\include\dm1\mutex.h"\
	"..\..\include\dm1\port.h"\
	"..\..\include\dm1\thread.h"\
	

..\..\src\threads\thread.cpp : \
	"..\..\include\dm1\common.h"\
	"..\..\include\dm1\event.h"\
	"..\..\include\dm1\except.h"\
	"..\..\include\dm1\list.h"\
	"..\..\include\dm1\mutex.h"\
	"..\..\include\dm1\port.h"\
	"..\..\include\dm1\thread.h"\
	

..\..\src\threads\threadpool.cpp : \
	"..\..\include\dm1\common.h"\
	"..\..\include\dm1\event.h"\
	"..\..\include\dm1\except.h"\
	"..\..\include\dm1\list.h"\
	"..\..\include\dm1\monitor.h"\
	"..\..\include\dm1\mutex.h"\
	"..\..\include\dm1\port.h"\
	"..\..\include\dm1\thread.h"\
	"..\..\include\dm1\threadpool.h"\
	
