# Generated automatically from Makefile.in by configure.
# Build yase

SHELL = /bin/sh

top_srcdir = ..
srcdir = .

prefix = /home/dibyendu/yase
examplesdir = $(prefix)/examples

INSTALLFILES = yase_search.html yase_html.template
DISTFILES = $(INSTALLFILES) alice.xml yase.dtd Makefile.in 

distdir = $(top_srcdir)/$(DISTNAME)/examples

clean:

dist:
	$(top_srcdir)/mkinstalldirs $(distdir) 
	cp $(DISTFILES) $(distdir)

install:
	$(top_srcdir)/mkinstalldirs $(examplesdir)
	cp $(INSTALLFILES) $(examplesdir)
