# Generated automatically from Makefile.in by configure.
# Build yase

SHELL = /bin/sh

top_srcdir = ..
srcdir = .

DISTFILES = Makefile.in test.btree.* testyq

distdir = $(top_srcdir)/$(DISTNAME)/test

clean:

dist:
	$(top_srcdir)/mkinstalldirs $(distdir) 
	cp $(DISTFILES) $(distdir)

