# Generated automatically from Makefile.in by configure.
# Build yase

SHELL = /bin/sh

top_srcdir = ..
srcdir = .

DISTFILES = COPYING *.html *.css *.jpg Makefile.in

distdir = $(top_srcdir)/$(DISTNAME)/doc

clean:

dist:
	$(top_srcdir)/mkinstalldirs $(distdir) 
	cp $(DISTFILES) $(distdir)

